using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TaskTrack.Repo.Models;

/// <summary>
/// Generated by: dotnet ef dbcontext scaffold "&lt;connection&gt;" Npgsql.EntityFrameworkCore.PostgreSQL
///   -o Models --context TaskManagementContext --no-onconfiguring
/// Post-scaffold edits (schema NOT changed):
///  1. Entity "Task" renamed to "TaskItem" (ToTable("Task") keeps the mapping).
///  2. Removed HasDefaultValue(...) on IsActive / Priority / Status: EF skips a property whose
///     value equals the CLR default, so IsActive=false or Priority=0 would silently become the
///     DB default. The service layer always sets these values explicitly instead.
/// The connection string is supplied from appsettings.json / DATABASE_URL in Program.cs.
/// </summary>
public partial class TaskManagementContext : DbContext
{
    public TaskManagementContext(DbContextOptions<TaskManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<TaskItem> Tasks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.DepartmentId).HasName("Department_pkey");

            entity.ToTable("Department");

            entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");
            entity.Property(e => e.DepartmentDescription)
                .HasMaxLength(300)
                .HasColumnName("DepartmentDescription");
            entity.Property(e => e.DepartmentName)
                .HasMaxLength(100)
                .HasColumnName("DepartmentName");
            entity.Property(e => e.IsActive).HasColumnName("IsActive");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.ProjectId).HasName("Project_pkey");

            entity.ToTable("Project");

            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("CreatedDate");
            entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");
            entity.Property(e => e.Description).HasColumnName("Description");
            entity.Property(e => e.EndDate).HasColumnName("EndDate");
            entity.Property(e => e.IsActive).HasColumnName("IsActive");
            entity.Property(e => e.ProjectName)
                .HasMaxLength(200)
                .HasColumnName("ProjectName");
            entity.Property(e => e.StartDate).HasColumnName("StartDate");
            entity.Property(e => e.Status).HasColumnName("Status");

            entity.HasOne(d => d.Department).WithMany(p => p.Projects)
                .HasForeignKey(d => d.DepartmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Project_Department");
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("Tag_pkey");

            entity.ToTable("Tag");

            entity.HasIndex(e => e.TagName, "Tag_TagName_key").IsUnique();

            entity.Property(e => e.TagId).HasColumnName("TagID");
            entity.Property(e => e.Color)
                .HasMaxLength(7)
                .HasColumnName("Color");
            entity.Property(e => e.TagName)
                .HasMaxLength(50)
                .HasColumnName("TagName");
        });

        modelBuilder.Entity<TaskItem>(entity =>
        {
            entity.HasKey(e => e.TaskId).HasName("Task_pkey");

            entity.ToTable("Task");

            entity.Property(e => e.TaskId).HasColumnName("TaskID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("CreatedDate");
            entity.Property(e => e.Description).HasColumnName("Description");
            entity.Property(e => e.DueDate).HasColumnName("DueDate");
            entity.Property(e => e.IsActive).HasColumnName("IsActive");
            entity.Property(e => e.ModifiedDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("ModifiedDate");
            entity.Property(e => e.Priority).HasColumnName("Priority");
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.Status).HasColumnName("Status");
            entity.Property(e => e.Title)
                .HasMaxLength(300)
                .HasColumnName("Title");

            entity.HasOne(d => d.Project).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Task_Project");

            entity.HasMany(d => d.Tags).WithMany(p => p.Tasks)
                .UsingEntity<Dictionary<string, object>>(
                    "TaskTag",
                    r => r.HasOne<Tag>().WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TaskTag_Tag"),
                    l => l.HasOne<TaskItem>().WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TaskTag_Task"),
                    j =>
                    {
                        j.HasKey("TaskId", "TagId").HasName("PK_TaskTag");
                        j.ToTable("TaskTag");
                        j.IndexerProperty<int>("TaskId").HasColumnName("TaskID");
                        j.IndexerProperty<int>("TagId").HasColumnName("TagID");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
